<%@ Page Title="" Language="C#" MasterPageFile="~/Content/AddressBook.master" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="AdminPanel_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="cphHead" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cphMainContent" Runat="Server">


   <div class="justify-content-around">Eighty-three individual athletes won medals at the 1928 Winter Olympics, which were held in St. Moritz, Switzerland, from February 11 to February 18, 1928. A total of 464 athletes from 25 National Olympic Committees (NOCs) participated in the 1928 Winter Olympics. Athletes representing Norway far surpassed their competitors in the medal count, winning fifteen medals to the six won by the nearest NOC, the United States. Twelve of the participating NOCs secured at least one medal, and among these, six NOCs won at least one gold medal. Sonja Henie (pictured) of Norway won the gold medal in the women's individual figure skating competition, the first of three consecutive Winter Olympics at which she would do so. Competing with an injured knee, Swedish figure skater Gillis Grafström won the men's individual competition at the third consecutive Winter Games. Norwegian speed skater Bernt Evensen topped the medal count, winning one gold, one silver, and one bronze medal. (Full list...)</div>
  <br />
    <div class="justify-content-around">Eighty-three individual athletes won medals at the 1928 Winter Olympics, which were held in St. Moritz, Switzerland, from February 11 to February 18, 1928. A total of 464 athletes from 25 National Olympic Committees (NOCs) participated in the 1928 Winter Olympics. Athletes representing Norway far surpassed their competitors in the medal count, winning fifteen medals to the six won by the nearest NOC, the United States. Twelve of the participating NOCs secured at least one medal, and among these, six NOCs won at least one gold medal. Sonja Henie (pictured) of Norway won the gold medal in the women's individual figure skating competition, the first of three consecutive Winter Olympics at which she would do so. Competing with an injured knee, Swedish figure skater Gillis Grafström won the men's individual competition at the third consecutive Winter Games. Norwegian speed skater Bernt Evensen topped the medal count, winning one gold, one silver, and one bronze medal. (Full list...)</div>
  <br />
    <div class="justify-content-around">Eighty-three individual athletes won medals at the 1928 Winter Olympics, which were held in St. Moritz, Switzerland, from February 11 to February 18, 1928. A total of 464 athletes from 25 National Olympic Committees (NOCs) participated in the 1928 Winter Olympics. Athletes representing Norway far surpassed their competitors in the medal count, winning fifteen medals to the six won by the nearest NOC, the United States. Twelve of the participating NOCs secured at least one medal, and among these, six NOCs won at least one gold medal. Sonja Henie (pictured) of Norway won the gold medal in the women's individual figure skating competition, the first of three consecutive Winter Olympics at which she would do so. Competing with an injured knee, Swedish figure skater Gillis Grafström won the men's individual competition at the third consecutive Winter Games. Norwegian speed skater Bernt Evensen topped the medal count, winning one gold, one silver, and one bronze medal. (Full list...)</div>
  <br />
    <div class="justify-content-around">Eighty-three individual athletes won medals at the 1928 Winter Olympics, which were held in St. Moritz, Switzerland, from February 11 to February 18, 1928. A total of 464 athletes from 25 National Olympic Committees (NOCs) participated in the 1928 Winter Olympics. Athletes representing Norway far surpassed their competitors in the medal count, winning fifteen medals to the six won by the nearest NOC, the United States. Twelve of the participating NOCs secured at least one medal, and among these, six NOCs won at least one gold medal. Sonja Henie (pictured) of Norway won the gold medal in the women's individual figure skating competition, the first of three consecutive Winter Olympics at which she would do so. Competing with an injured knee, Swedish figure skater Gillis Grafström won the men's individual competition at the third consecutive Winter Games. Norwegian speed skater Bernt Evensen topped the medal count, winning one gold, one silver, and one bronze medal. (Full list...)</div>
  <br />
    <div class="justify-content-around">Eighty-three individual athletes won medals at the 1928 Winter Olympics, which were held in St. Moritz, Switzerland, from February 11 to February 18, 1928. A total of 464 athletes from 25 National Olympic Committees (NOCs) participated in the 1928 Winter Olympics. Athletes representing Norway far surpassed their competitors in the medal count, winning fifteen medals to the six won by the nearest NOC, the United States. Twelve of the participating NOCs secured at least one medal, and among these, six NOCs won at least one gold medal. Sonja Henie (pictured) of Norway won the gold medal in the women's individual figure skating competition, the first of three consecutive Winter Olympics at which she would do so. Competing with an injured knee, Swedish figure skater Gillis Grafström won the men's individual competition at the third consecutive Winter Games. Norwegian speed skater Bernt Evensen topped the medal count, winning one gold, one silver, and one bronze medal. (Full list...)</div>
  <br />
</asp:Content>

